#!/usr/bin/python3

a = 10
b = 5

import calculator_1

result_add = calculator_1.add(a, b)
result_subtract = calculator_1.subtract(a, b)
result_multiply = calculator_1.multiply(a, b)
result_divide = calculator_1.divide(a, b)

print(f"{a} + {b} =", result_add)
print(f"{a} - {b} =", result_subtract)
print(f"{a} * {b} =", result_multiply)
print(f"{a} / {b} =", result_divide)
