#!/usr/bin/python3
from calculator_1 import add, sub, mul, div

# Defining variables
a = 10
b = 5

if __name__ == "__main__":
    # Calling functions and storing results
    sum_result = add(a, b)
    diff_result = sub(a, b)
    prod_result = mul(a, b)
    quot_result = div(a, b)

    # Printing the results with limited print statements
    print(f"{a} + {b} = {sum_result}")
    print(f"{a} - {b} = {diff_result}")
    print(f"{a} * {b} = {prod_result}")
    print(f"{a} / {b} = {quot_result}")

